unstable_features = true
indent_style = "Block"
brace_style = "PreferSameLine"
use_field_init_shorthand = true
hard_tabs = true
tab_spaces = 4
max_width = 120
wrap_comments = true
remove_trailing_whitespace = true
multiline_style = "PreferSingle"
struct_lit_style = "Block"
single_line_if_else_max_width = 100
fn_args_density = "Tall"
where_single_line = true
fn_single_line = true
format_macro_matches = true
format_macro_bodies = true
empty_item_single_line = true
