fn_brace_style = "PreferSameLine"
unstable_features = true
hard_tabs = true
tab_spaces = 4
max_width = 120
wrap_comments = true
remove_trailing_whitespace = true
multiline_style = "PreferSingle"
struct_lit_style = "Block"
single_line_if_else_max_width = 80
fn_args_density = "Compressed"
where_single_line = true
fn_single_line = true
format_macro_matches = true
format_macro_bodies = true
