fn_brace_style = "PreferSameLine"
hard_tabs = true
max_width = 120
remove_trailing_whitespace = true
multiline_style = "PreferSingle"
struct_lit_style = "Block"
density = "Compressed"
single_line_if_else_max_width = 80

