[package]

name = "rust-oids"
version = "0.2.0"
authors = [
	"norru <nigu.orru@gmail.com>"
]

[[bin]]
name = "rust-oids"
path = "src/main.rs"

[dependencies]
num ="0.1.32"
log="0.3.6"
itertools = "0.4.18"
simplelog="0.1.0"
cgmath="0.7"
rand = "0.3"
mopa ="0.2"
genmesh="0.4"
bitflags="*"
bit-set="*"

image = "*"
piston = "*"
wrapped2d = "*"
gfx = "*"
gfx_core = "*"
gfx_device_gl = "*"
gfx_window_glutin = "*"
gfx_text = "*"
glutin = "*"

synth="*"
