[package]

name = "rust-evaluation"
version = "0.1.0"
authors = [
	"norru <nigu.orru@gmail.com>"
]

[[bin]]
name = "rust-evaluation"
path = "src/main.rs"

[dependencies]
num ="0.1.32"
log="0.3.6"
simplelog="0.1.0"
cgmath="0.7"
rand = "0.3"
mopa ="0.2"
genmesh="0.4"

piston = "*"
wrapped2d = "0.3.1"
gfx = "*"
gfx_core = "*"
gfx_device_gl = "*"
gfx_window_glutin = "*"
gfx_text = "*"
glutin = "*"
