[package]
name = "rust-oids"
version = "0.5.0"
authors = [
	"norru <nigu.orru@gmail.com>"
]

[[bin]]
name = "rust-oids"
path = "src/main.rs"

[dependencies]
num ="*"
log="*"
itertools = "*"
log4rs = "*"
cgmath="*"
rand = "*"
chrono="*"
enum_primitive="*"
bitflags="*"
bit-set="*"
csv = "*"
rustc-serialize="*"
image = "*"
wrapped2d = "*"
glutin = "*"
gfx = "*"
gfx_core = "*"
gfx_device_gl = "*"
#sound
dsp-chain="*"
sample="*"
portaudio="*"

#sys
thread-priority = "*"
ctrlc = "*"
getopts = "*"

#gui
winit = "*"
gfx_window_glutin = "*"
conrod = { features = ["gfx_rs", "winit"], version = "*" }
