[package]
name = "rust-oids"
version = "0.7.0"
authors = [
	"norru <nigu.orru@gmail.com>"
]

[[bin]]
name = "rust-oids"
path = "src/main.rs"

[dependencies]
num ="*"
num-traits="*"
log="*"
itertools = "*"
log4rs = "*"
cgmath="*"
rand = "*"
chrono="*"
enum_primitive="*"
bitflags="*"
bit-set="*"
csv = "*"
rustc-serialize="*"
image = "*"
wrapped2d = "*"
glutin = "0.11.0"
gfx = "0.16.2"
gfx_core = "0.7.2"
gfx_device_gl = "0.14.6"
#sound
sample="*"
pitch_calc="*"
portaudio="*"

#sys
ctrlc = "*"
getopts = "*"

#gui
winit = "*"
gfx_window_glutin = "0.19.0"
conrod = { features = ["winit"], version = "*" }
#
[target.'cfg(unix)'.dependencies]
thread-priority = "*"
