[package]

name = "rust-oids"
version = "0.3.0"
authors = [
	"norru <nigu.orru@gmail.com>"
]

[[bin]]
name = "rust-oids"
path = "src/main.rs"

[dependencies]
num ="*"
log="*"
itertools = "*"
log4rs = "*"
cgmath="*"
rand = "*"
chrono="*"
enum_primitive="*"
bitflags="*"
bit-set="*"
csv = "*"
custom_derive="*"
enum_derive="*"
rustc-serialize="*"
image = "*"
piston = "*"
wrapped2d = "*"
glutin = "*"
winit = "*"
gfx = "*"
gfx_core = "*"
gfx_device_gl = "*"
gfx_window_glutin = "*"
gfx_text = "*"

sampler="*"
