[package]

name = "rust-oids"
version = "0.3.0"
authors = [
	"norru <nigu.orru@gmail.com>"
]

[[bin]]
name = "rust-oids"
path = "src/main.rs"

[dependencies]
num ="0.1.32"
log="0.3.6"
itertools = "0.4.18"
log4rs = "0.4.8"
cgmath="0.7"
rand = "0.3"
chrono="0.2.25"
enum_primitive="*"
bitflags="*"
bit-set="*"
csv = "*"
custom_derive="*"
enum_derive="*"
rustc-serialize="*"
image = "*"
piston = "*"
wrapped2d = "*"
glutin = "0.6.2"
gfx = "*"
gfx_core = "*"
gfx_device_gl = "*"
gfx_window_glutin = "*"
gfx_text = "*"

sampler="*"
