[package]

name = "getting-started-spinning-square"
version = "0.1.0"
authors = [
    "TyOverby <ty@pre-alpha.com>",
    "Nikita Pekin <contact@nikitapek.in>"
]

[[bin]]
name = "spinning-square"

[dependencies]
piston = "0.22.0"
piston2d-graphics = "0.16.0"
pistoncore-glutin_window = "0.26.0"
piston2d-opengl_graphics = "0.28.0"
rand = "0.3"
wrapped2d = { git = "https://github.com/itadinanta/rust_box2d.git", commit = "830d3e108504cb87a7035d54712d202acf02ad33"}
