[package]
name = "rust-oids"
version = "0.5.0"
authors = [
	"norru <nigu.orru@gmail.com>"
]

[[bin]]
name = "rust-oids"
path = "src/main.rs"

[dependencies]
num ="*"
log="*"
itertools = "*"
log4rs = "*"
cgmath="*"
rand = "*"
chrono="*"
enum_primitive="*"
bitflags="*"
bit-set="*"
csv = "*"
rustc-serialize="*"
image = "*"
wrapped2d = "*"
gfx = "*"
gfx_core = "*"

# ui
winit = "*"
glutin = "*"
gfx_device_gl = "*"
gfx_window_glutin = "*"
gfx_text = "*"
conrod = { version = "*", features = ["winit", "gfx_rs"]  }

#sound
dsp-chain="*"
sample="*"
portaudio="*"

#sys
getopts = "*"
ctrlc = "*"
thread-priority = "*"

