[package]

name = "rust-evaluation"
version = "0.1.0"
authors = [
	"norru <nigu.orru@gmail.com>"
]

[[bin]]
name = "rust-evaluation"

[dependencies]
piston = "0.22.0"
piston2d-graphics = "0.16.0"
pistoncore-glutin_window = "0.26.0"
piston2d-opengl_graphics = "0.28.0"
rand = "0.3"
wrapped2d = { git = "https://github.com/itadinanta/rust_box2d.git", branch = "master"}
